### PR TITLE
Port to 1.21

### LINKED ISSUE #10: Update to 1.21?
Is there any plans about updating this mod to newest version and if it is, how could we help with that?

### PR DESCRIPTION
**Pull request by Dianliang233**
Fixes #10

This PR upgrade relevant dependencies and fix method calls. However, tabs doesn't seem to work properly, and I don't have enough experience with this kind of stuff to figure out why.

@Blobanium

### CODE REVIEW

**Comment by Blobanium** [comment]
Nvm ignore those 2 reviews, now i know why.

**Comment by Blobanium** [comment]
i was able to fix the scaling issues with the tab buttons, it seems that there was a similar issue with the reload button also. it was that you had your arguments when calling `drawGuiTexture` in the wrong places.

**Comment by Blobanium** [comment]
@Dianliang233 i could merge this PR rn if you want me to. I can fix the issue with the tabs in a future update myself.

**Comment by Dianliang233** [comment]
Let's have a new release only if all the issues are fixed.

**Comment by Blobanium** [comment]
alr no worries, 

> Let's have a new release only if all the issues are fixed.
> 
> (IMO you can merge this, fix all the bugs, then have a new release)

alr no problem, i will fix everything else myself and then push the release. 

I will merge this PR right now.

**Comment by Blobanium** [comment]
i will be merging this PR now. Thanks for contributing to MCBrowser!

**Comment by Someguy-hq** [comment]
can you just update it idc how many bugs there are 🙏

**Comment by Blobanium** [comment]
> can you just update it idc how many bugs there are 🙏

I just pushed an update for 1.21 just now

https://github.com/Blobanium/MCBrowser/releases/tag/v1.1.0-Alpha1
https://modrinth.com/mod/mcbrowser/version/CcY6AeJ7

**Pull request merged**
